[haproxy]
haproxy ansible_host=192.168.85.10 
[masters]
master1 ansible_host=192.168.85.101 
master2 ansible_host=192.168.85.102 
master3 ansible_host=192.168.85.103 

[worker]
worker1 ansible_host=192.168.85.201 
worker2 ansible_host=192.168.85.202 
worker3 ansible_host=192.168.85.203 
worker4 ansible_host=192.168.85.204 

[all:vars]
lb_ip=192.168.85.10
ansible_become=true
ansible_user=vagrant
ansible_password=vagrant
ansible_ssh_common_args='-o StrictHostKeyChecking=no'


