[haproxy]
haproxy ansible_host=192.168.85.10 ansible_user=master01 ansible_become=true

[masters]
master01 ansible_host=192.168.85.101 ansible_user=master01 ansible_become=true
master02 ansible_host=192.168.85.102 ansible_user=master02 ansible_become=true
master03 ansible_host=192.168.85.103 ansible_user=master03 ansible_become=true

[worker]
node01 ansible_host=192.168.85.201 ansible_user=node01 ansible_become=true
node02 ansible_host=192.168.85.202 ansible_user=node02 ansible_become=true
node03 ansible_host=192.168.85.203 ansible_user=node03 ansible_become=true
node04 ansible_host=192.168.85.204 ansible_user=node04 ansible_become=true

[all:vars]
lb_ip=192.168.85.10
ansible_become=true
ansible_user=vagrant
ansible_password=vagrant
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

